CREATE DATABASE CUSTOMERS_DB;
USE CUSTOMERS_DB;

CREATE TABLE CUSTOMERS (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(100),
    Email VARCHAR(100),
    Age INT
);

UPDATE CUSTOMERS
SET Email = CONCAT('user', CustomerID, '@example.com')
WHERE Email IS NULL;

UPDATE CUSTOMERS
SET FullName = 'Unknown'
WHERE FullName IS NULL;

UPDATE CUSTOMERS
SET Age = 0
WHERE Age < 0 OR Age IS NULL;

ALTER TABLE CUSTOMERS
MODIFY Email VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS
MODIFY FullName VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS
ADD CONSTRAINT chk_age CHECK (Age >= 0 AND Age <= 120);

ALTER TABLE CUSTOMERS
ADD CONSTRAINT unique_email UNIQUE (Email);